## 00. PyTorch Fundamentals

In [1]:
import torch
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim, scalar.shape

(0, torch.Size([]))

In [4]:
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim, vector.shape

(1, torch.Size([2]))

In [7]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [1, 2]])
MATRIX

tensor([[7, 8],
        [1, 2]])

In [8]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [9]:
MATRIX[1, 0].item()

1

In [10]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

In [12]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [13]:
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.ndim, random_tensor.shape

(tensor([[0.7133, 0.5341, 0.8003, 0.2428],
         [0.8819, 0.3391, 0.7922, 0.2098],
         [0.3539, 0.8885, 0.0487, 0.5362]]),
 2,
 torch.Size([3, 4]))

In [14]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [15]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [18]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arange_tensor = torch.arange(start=0, end=1000, step=77)
arange_tensor

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [20]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

In [22]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,
                               device=None,
                               requires_grad=False)

float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [23]:
float_16_tensor = torch.tensor([3.0, 5.0, 9.0],
                               dtype=torch.half)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 5., 9.], dtype=torch.float16), torch.float16)

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [25]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [26]:
int_32_tensor = torch.tensor([3, 2, 9],
                             dtype=torch.int32)

In [27]:
(float_32_tensor * int_32_tensor).dtype

torch.float32

### Getting information from Tensors

In [28]:
some_tensor = torch.rand((3, 5),
                         device="cuda")
some_tensor

tensor([[0.5830, 0.2604, 0.3586, 0.6573, 0.8476],
        [0.3282, 0.1824, 0.7422, 0.0330, 0.9237],
        [0.5978, 0.7719, 0.4707, 0.9080, 0.1557]], device='cuda:0')

In [29]:
some_tensor.dtype, some_tensor.shape, some_tensor.device, some_tensor.size()

(torch.float32,
 torch.Size([3, 5]),
 device(type='cuda', index=0),
 torch.Size([3, 5]))

### Manipulating Tensors

In [30]:
tensor_1 = torch.tensor([1, 2, 3])
tensor_1 + tensor_1

tensor([2, 4, 6])

In [31]:
tensor_1 * tensor_1

tensor([1, 4, 9])

In [32]:
tensor_1 - 10, tensor_1 - tensor_1

(tensor([-9, -8, -7]), tensor([0, 0, 0]))

In [33]:
torch.add(tensor_1, 2)

tensor([3, 4, 5])

In [34]:
torch.mul(tensor_1, 3)

tensor([3, 6, 9])

In [35]:
torch.sub(tensor_1, 1)

tensor([0, 1, 2])

### Matrix multiplication

In [36]:
 # Element wise multiplication
tensor_1 * tensor_1

tensor([1, 4, 9])

In [37]:
# Matrix multiplication
torch.matmul(tensor_1, tensor_1)

tensor(14)

In [38]:
%%time
value = 0
for i in range(len(tensor_1)):
  value += tensor_1[i] * tensor_1[i]

value

CPU times: user 349 µs, sys: 1.09 ms, total: 1.44 ms
Wall time: 4.7 ms


tensor(14)

In [39]:
%%time
torch.matmul(tensor_1, tensor_1)

CPU times: user 41 µs, sys: 0 ns, total: 41 µs
Wall time: 43.9 µs


tensor(14)

In [40]:
tensor_1 = torch.arange(0, 500000)

In [41]:
%%time
torch.matmul(tensor_1, tensor_1)

CPU times: user 1.53 ms, sys: 0 ns, total: 1.53 ms
Wall time: 2.53 ms


tensor(41666541666750000)

### One of the most error in deep learning is: Shape Error

In [42]:
tensor_1 @ tensor_1

tensor(41666541666750000)

In [43]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

In [44]:
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [45]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [46]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [47]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [50]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [52]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [54]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [55]:
# Find the min index
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [56]:
# Find dthe max index
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors

In [67]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [62]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [68]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [69]:
z[:,0] = 1000
x

tensor([1000.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.])

In [72]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1000., 1000., 1000., 1000.],
        [   2.,    2.,    2.,    2.],
        [   3.,    3.,    3.,    3.],
        [   4.,    4.,    4.,    4.],
        [   5.,    5.,    5.,    5.],
        [   6.,    6.,    6.,    6.],
        [   7.,    7.,    7.,    7.],
        [   8.,    8.,    8.,    8.],
        [   9.,    9.,    9.,    9.]])

In [73]:
v_stacked = torch.vstack([x, x, x, x])
v_stacked

tensor([[1000.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.],
        [1000.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.],
        [1000.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.],
        [1000.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.]])

In [76]:
h_stacked = torch.hstack([x, x, x, x])
h_stacked

tensor([1000.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9., 1000.,
           2.,    3.,    4.,    5.,    6.,    7.,    8.,    9., 1000.,    2.,
           3.,    4.,    5.,    6.,    7.,    8.,    9., 1000.,    2.,    3.,
           4.,    5.,    6.,    7.,    8.,    9.])

In [78]:
y = torch.arange(0, 10)
y, y.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [80]:
y = y.reshape(1, 10)
y, y.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [82]:
y = y.squeeze()
y, y.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [89]:
y.unsqueeze(dim=1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [100]:
y.reshape(1, 10, 1, 1).squeeze()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
# torch.unsqueeze()
y, y.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [99]:
y = y.unsqueeze(dim=4)
y

tensor([[[[[0],
           [1],
           [2],
           [3],
           [4],
           [5],
           [6],
           [7],
           [8],
           [9]]]]])

In [101]:
# torch.permute
x_org = torch.rand(size=(224, 224, 3))
x_permute = x_org.permute(2, 0, 1)
x_permute.shape

torch.Size([3, 224, 224])