## 00. PyTorch Fundamentals

In [2]:
import torch
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim, scalar.shape

(0, torch.Size([]))

In [7]:
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [11]:
vector.ndim, vector.shape

(1, torch.Size([2]))

In [13]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [1, 2]])
MATRIX

tensor([[7, 8],
        [1, 2]])

In [14]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [17]:
MATRIX[1, 0].item()

1

In [18]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [28]:
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.ndim, random_tensor.shape

(tensor([[0.4505, 0.6413, 0.9554, 0.6468],
         [0.6056, 0.8927, 0.2160, 0.6861],
         [0.8050, 0.1514, 0.2969, 0.7310]]),
 2,
 torch.Size([3, 4]))

In [29]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [32]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [55]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arange_tensor = torch.arange(start=0, end=1000, step=77)
arange_tensor

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [58]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])