## 00. PyTorch Fundamentals

In [1]:
import torch
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim, scalar.shape

(0, torch.Size([]))

In [7]:
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [11]:
vector.ndim, vector.shape

(1, torch.Size([2]))

In [13]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [1, 2]])
MATRIX

tensor([[7, 8],
        [1, 2]])

In [14]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [17]:
MATRIX[1, 0].item()

1

In [18]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [28]:
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.ndim, random_tensor.shape

(tensor([[0.4505, 0.6413, 0.9554, 0.6468],
         [0.6056, 0.8927, 0.2160, 0.6861],
         [0.8050, 0.1514, 0.2969, 0.7310]]),
 2,
 torch.Size([3, 4]))

In [29]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [32]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [55]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arange_tensor = torch.arange(start=0, end=1000, step=77)
arange_tensor

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [58]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

In [72]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,
                               device=None,
                               requires_grad=False)

float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [73]:
float_16_tensor = torch.tensor([3.0, 5.0, 9.0],
                               dtype=torch.half)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 5., 9.], dtype=torch.float16), torch.float16)

In [74]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [76]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [77]:
int_32_tensor = torch.tensor([3, 2, 9],
                             dtype=torch.int32)

In [79]:
(float_32_tensor * int_32_tensor).dtype

torch.float32

### Getting information from Tensors

In [2]:
some_tensor = torch.rand((3, 5),
                         device="cuda")
some_tensor

tensor([[0.0649, 0.1744, 0.0249, 0.3896, 0.1262],
        [0.7941, 0.9020, 0.4711, 0.4552, 0.2339],
        [0.7327, 0.0374, 0.3290, 0.1865, 0.8203]], device='cuda:0')

In [3]:
some_tensor.dtype, some_tensor.shape, some_tensor.device, some_tensor.size()

(torch.float32,
 torch.Size([3, 5]),
 device(type='cuda', index=0),
 torch.Size([3, 5]))

### Manipulating Tensors

In [5]:
tensor_1 = torch.tensor([1, 2, 3])
tensor_1 + tensor_1

tensor([2, 4, 6])

In [7]:
tensor_1 * tensor_1

tensor([1, 4, 9])

In [9]:
tensor_1 - 10, tensor_1 - tensor_1

(tensor([-9, -8, -7]), tensor([0, 0, 0]))

In [10]:
torch.add(tensor_1, 2)

tensor([3, 4, 5])

In [11]:
torch.mul(tensor_1, 3)

tensor([3, 6, 9])

In [12]:
torch.sub(tensor_1, 1)

tensor([0, 1, 2])