In [6]:
import tensorflow as tf
import numpy as np 
import random

In [4]:
X_train = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
y_train = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

In [19]:
w = tf.Variable(random.random(), trainable=True)
b = tf.Variable(random.random(), trainable=True)

In [9]:
#loss function
def simple_loss(real_y, pred_y):
    return tf.abs(real_y - pred_y)


In [10]:
LEARNING_RATE = 0.001

In [14]:
def fit_data(real_x, real_y):
    with tf.GradientTape(persistent=True) as tape:
        # Make prediction
        pred_y = w * real_x + b
        
        # Calculate loss
        reg_loss = simple_loss(real_y, pred_y)
        
    # Calculate gradients
    w_gradient = tape.gradient(reg_loss, w)
    b_gradient = tape.gradient(reg_loss, b)
    
    # Update variables
    w.assign_sub(w_gradient * LEARNING_RATE)
    b.assign_sub(b_gradient * LEARNING_RATE)

In [16]:
for epoch in range(500):
    fit_data(X_train, y_train)
    
print(f'y = {w.numpy()}x + {b.numpy()}')

y = 2.0032787322998047x + -0.9969756007194519


In [24]:
w = tf.Variable([2.0])
with tf.GradientTape() as tape:
    loss = w * w * w
tape.gradient(loss, w)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([12.], dtype=float32)>

In [34]:
x = tf.Variable([[1, 1],
                  [1,1]], dtype="float32")

with tf.GradientTape() as tape:
    tape.watch(x)
    
    y = tf.reduce_sum(x)
    z = tf.square(y)

dz_dx = tape.gradient(z, x)
y, z, dz_dx

(<tf.Tensor: shape=(), dtype=float32, numpy=4.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=16.0>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[8., 8.],
        [8., 8.]], dtype=float32)>)

In [37]:
x = tf.constant(3.0)
with tf.GradientTape(persistent=True) as t:
    t.watch(x)
    y = x * x
    z = y * y
dz_dx = t.gradient(z, x)
dy_dx = t.gradient(y, x)
dz_dy = t.gradient(z, y)
dz_dx, dy_dx, dz_dy

(<tf.Tensor: shape=(), dtype=float32, numpy=108.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=18.0>)

In [40]:
x = tf.Variable(3.0)
with tf.GradientTape() as tape_2:
    with tf.GradientTape() as tape_1:
        y = x * x * x
    dy_dx = tape_1.gradient(y, x)
d2y_dx2 = tape_2.gradient(dy_dx, x)
dy_dx, d2y_dx2

(<tf.Tensor: shape=(), dtype=float32, numpy=27.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=18.0>)